name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build 
      run: |
        ./build.sh && for s in ./*2*py ; do $s --help ; done && sudo pip3 install -U -r test-requirements.txt && pylint -E *py && pytype -k *py && pytest --cov-report term --cov=sidlib --cov=sidwav --cov=ssf --cov=sidmidi --cov=sidreg
