name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build 
      run: |
        sudo apt-get update && sudo apt-get install python3-dev && \
        sudo pip3 install . && \
        sudo pip3 install -U -r test-requirements.txt && \
        PYFILES=$(find . -type f -name \*py)
        pylint -E ${PYFILES} && pytype -k ${PYFILES} && \
        coverage run --source=. -m unittest discover && coverage report -m
